=== Bencuriusz/F6MYAZ_XMLGyak/F6MYAZ_1006/BB_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="konyvek">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="konyv">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cim" type="xs:string" />
                            <xs:element name="ev" type="xs:unsignedShort" />
                            <xs:element name="kiado" type="xs:string" />
                            <xs:element name="iro" type="xs:string" maxOccurs="unbounded" />
                            <xs:element name="kivonat" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Bencuriusz/F6MYAZ_XMLGyak/F6MYAZ_1006/BB_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>
<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BB_konyv.xsd">

    <konyv id="k01">
        <cim>
         Grafikus és játékalkalmazások programozása       
         </cim>
        <ev>2017</ev>
        <kiado>BBS-INFO KÖNYVK. ÉS INFORM. KFT.</kiado>
        <szerzo>Fehér Krisztián</szerzo>
        <kivonat>kivonat</kivonat>
    </konyv>
    <konyv id="k02">
        <cim>
            PHP és MySQL az alapoktól       
        </cim>
        <ev>2011</ev>
        <kiado>BBS-INFO KÖNYVK. ÉS INFORM. KFT.</kiado>
        <szerzo>Kozmajer Viktor</szerzo>
        <kivonat>kivonat</kivonat>
    </konyv>
    <konyv id="k03">
        <cim>
            The Pragmatic Programmer: From Journeyman to Master
        </cim>
        <ev>1999</ev>
        <kiado>Addison-Wesley Professional</kiado>
        <szerzo>David Thomas</szerzo>
        <szerzo>Andrew Hun</szerzo>
        <kivonat>kivonat</kivonat>
    </konyv>

</konyvek>
